### ISSUE TITLE
Ficha de entrada

### ISSUE THREAD

**Issue by fatimaTalavera** [Jorge199/SD16#5]
la fecha de ingreso debe ser la fecha actual
quitar el requerido en observaciones
el codigo debe ser autogenerado, hacer fecha de ingreso + numero (consultar con el doctor), agregar en el api Nro de casets y laminas para evitar parsear el codigo
cambiar los campos disable por readonly
verificar la validacion del codigo

**Comment by taniamonges** [comment]
agrega campo especimen
